import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import { DirectionProvider } from "@/registry/dga/ui/direction"

import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  let lang = "en"
  const dir = lang === "ar" ? "rtl" : "ltr"
  return (
    <html
      lang={lang}
      dir={dir}
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <DirectionProvider dir={dir} direction={dir}>
          {children}       
        </DirectionProvider>
      </body>
    </html>
  )
}
