import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DirectionProvider } from "@/registry/dga/ui/direction";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ar"
      dir="ltr"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <DirectionProvider dir="rtl" direction="rtl">{children}</DirectionProvider>
      </body>
    </html>
  );
}
